import { iExtractFile } from '@/interfaces/ShopifyFujifilmOrder'

export const extractFileConfig: { shopify: iExtractFile; shopee: iExtractFile; lazada: iExtractFile; productMaster: iExtractFile; tiktok: iExtractFile } = {
  shopify: {
    stringHeaderMapping: [
      'Name',
      'Email',
      'Financial Status',
      'Paid at',
      'Fulfillment Status',
      'Fulfilled at',
      'Accepts Marketing',
      'Currency',
      'Subtotal',
      'Shipping',
      'Taxes',
      'Total',
      'Discount Code',
      'Discount Amount',
      'Shipping Method',
      'Created at',
      'Lineitem quantity',
      'Lineitem name',
      'Lineitem price',
      'Lineitem compare at price',
      'Lineitem sku',
      'Lineitem requires shipping',
      'Lineitem taxable',
      'Lineitem fulfillment status',
      'Billing Name',
      'Billing Street',
      'Billing Address1',
      'Billing Address2',
      'Billing Company',
      'Billing City',
      'Billing Zip',
      'Billing Province',
      'Billing Country',
      'Billing Phone',
      'Shipping Name',
      'Shipping Street',
      'Shipping Address1',
      'Shipping Address2',
      'Shipping Company',
      'Shipping City',
      'Shipping Zip',
      'Shipping Province',
      'Shipping Country',
      'Shipping Phone',
      'Notes',
      'Note Attributes',
      'Cancelled at',
      'Payment Method',
      'Payment Reference',
      'Refunded Amount',
      'Vendor',
      'Outstanding Balance',
      'Employee',
      'Location',
      'Device ID',
      'Id',
      'Tags',
      'Risk Level',
      'Source',
      'Lineitem discount',
      'Tax 1 Name',
      'Tax 1 Value',
      'Tax 2 Name',
      'Tax 2 Value',
      'Tax 3 Name',
      'Tax 3 Value',
      'Tax 4 Name',
      'Tax 4 Value',
      'Tax 5 Name',
      'Tax 5 Value',
      'Phone',
      'Receipt Number',
      'Duties',
      'Billing Province Name',
      'Shipping Province Name',
      'Payment ID',
      'Payment Terms Name',
      'Next Payment Due At',
      'Payment References'
    ],
    objectColumnMapping: {
      A: 'name',
      B: 'email',
      C: 'financialStatus',
      D: 'paidAt',
      E: 'fulfillmentStatus',
      F: 'fulfilledAt',
      G: 'acceptsMarketing',
      H: 'currency',
      I: 'subtotal',
      J: 'shipping',
      K: 'taxes',
      L: 'total',
      M: 'discountCode',
      N: 'discountAmount',
      O: 'shippingMethod',
      P: 'createdAt',
      Q: 'lineitemQuantity',
      R: 'lineitemName',
      S: 'lineitemPrice',
      T: 'lineitemCompareAtPrice',
      U: 'lineitemSku',
      V: 'lineitemRequiresShipping',
      W: 'lineitemTaxable',
      X: 'lineitemFulfillmentStatus',
      Y: 'billingName',
      Z: 'billingStreet',
      AA: 'billingAddress1',
      AB: 'billingAddress2',
      AC: 'billingCompany',
      AD: 'billingCity',
      AE: 'billingZip',
      AF: 'billingProvince',
      AG: 'billingCountry',
      AH: 'billingPhone',
      AI: 'shippingName',
      AJ: 'shippingStreet',
      AK: 'shippingAddress1',
      AL: 'shippingAddress2',
      AM: 'shippingCompany',
      AN: 'shippingCity',
      AO: 'shippingZip',
      AP: 'shippingProvince',
      AQ: 'shippingCountry',
      AR: 'shippingPhone',
      AS: 'notes',
      AT: 'noteAttributes',
      AU: 'cancelledAt',
      AV: 'paymentMethod',
      AW: 'paymentReference',
      AX: 'refundedAmount',
      AY: 'vendor',
      AZ: 'outstandingBalance',
      BA: 'employee',
      BB: 'location',
      BC: 'deviceId',
      BD: 'id',
      BE: 'tags',
      BF: 'riskLevel',
      BG: 'source',
      BH: 'lineitemDiscount',
      BI: 'tax1Name',
      BJ: 'tax1Value',
      BK: 'tax2Name',
      BL: 'tax2Value',
      BM: 'tax3Name',
      BN: 'tax3Value',
      BO: 'tax4Name',
      BP: 'tax4Value',
      BQ: 'tax5Name',
      BR: 'tax5Value',
      BS: 'phone',
      BT: 'receiptNumber',
      BU: 'duties',
      BV: 'billingProvinceName',
      BW: 'shippingProvinceName',
      BX: 'paymentId',
      BY: 'paymentTermsName',
      BZ: 'nextPaymentDueAt',
      CA: 'paymentReferences'
    },
    stringColumnMapping: [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'M',
      'O',
      'P',
      'R',
      'U',
      'X',
      'Y',
      'Z',
      'AA',
      'AB',
      'AC',
      'AD',
      'AE',
      'AF',
      'AG',
      'AH',
      'AI',
      'AJ',
      'AK',
      'AL',
      'AM',
      'AN',
      'AO',
      'AP',
      'AQ',
      'AR',
      'AS',
      'AT',
      'AU',
      'AV',
      'AW',
      'AY',
      'BA',
      'BB',
      'BC',
      'BE',
      'BF',
      'BG',
      'BI',
      'BJ',
      'BK',
      'BL',
      'BM',
      'BN',
      'BO',
      'BP',
      'BQ',
      'BR',
      'BS',
      'BT',
      'BU',
      'BV',
      'BW',
      'BX',
      'BY',
      'BZ',
      'CA'
    ],
    numberColumnMapping: ['I', 'J', 'K', 'L', 'N', 'Q', 'S', 'T', 'V', 'W', 'AX', 'AZ', 'BD', 'BH'],
    headerObjectMapping: {
      Name: { keyName: 'name', type: 'string' },
      Email: { keyName: 'email', type: 'string' },
      'Financial Status': { keyName: 'financialStatus', type: 'string' },
      'Paid at': { keyName: 'paidAt', type: 'datetime' },
      'Fulfillment Status': { keyName: 'fulfillmentStatus', type: 'string' },
      'Fulfilled at': { keyName: 'fulfilledAt', type: 'string' },
      'Accepts Marketing': { keyName: 'acceptsMarketing', type: 'string' },
      Currency: { keyName: 'currency', type: 'string' },
      Subtotal: { keyName: 'subtotal', type: 'number' },
      Shipping: { keyName: 'shipping', type: 'number' },
      Taxes: { keyName: 'taxes', type: 'number' },
      Total: { keyName: 'total', type: 'number' },
      'Discount Code': { keyName: 'discountCode', type: 'string' },
      'Discount Amount': { keyName: 'discountAmount', type: 'number' },
      'Shipping Method': { keyName: 'shippingMethod', type: 'string' },
      'Created at': { keyName: 'createdAt', type: 'datetime' },
      'Lineitem quantity': { keyName: 'lineitemQuantity', type: 'number' },
      'Lineitem name': { keyName: 'lineitemName', type: 'string' },
      'Lineitem price': { keyName: 'lineitemPrice', type: 'number' },
      'Lineitem compare at price': { keyName: 'lineitemCompareAtPrice', type: 'number' },
      'Lineitem sku': { keyName: 'lineitemSku', type: 'string' },
      'Lineitem requires shipping': { keyName: 'lineitemRequiresShipping', type: 'boolean' },
      'Lineitem taxable': { keyName: 'lineitemTaxable', type: 'boolean' },
      'Lineitem fulfillment status': { keyName: 'lineitemFulfillmentStatus', type: 'string' },
      'Billing Name': { keyName: 'billingName', type: 'string' },
      'Billing Street': { keyName: 'billingStreet', type: 'string' },
      'Billing Address1': { keyName: 'billingAddress1', type: 'string' },
      'Billing Address2': { keyName: 'billingAddress2', type: 'string' },
      'Billing Company': { keyName: 'billingCompany', type: 'string' },
      'Billing City': { keyName: 'billingCity', type: 'string' },
      'Billing Zip': { keyName: 'billingZip', type: 'string' },
      'Billing Province': { keyName: 'billingProvince', type: 'string' },
      'Billing Country': { keyName: 'billingCountry', type: 'string' },
      'Billing Phone': { keyName: 'billingPhone', type: 'string' },
      'Shipping Name': { keyName: 'shippingName', type: 'string' },
      'Shipping Street': { keyName: 'shippingStreet', type: 'string' },
      'Shipping Address1': { keyName: 'shippingAddress1', type: 'string' },
      'Shipping Address2': { keyName: 'shippingAddress2', type: 'string' },
      'Shipping Company': { keyName: 'shippingCompany', type: 'string' },
      'Shipping City': { keyName: 'shippingCity', type: 'string' },
      'Shipping Zip': { keyName: 'shippingZip', type: 'string' },
      'Shipping Province': { keyName: 'shippingProvince', type: 'string' },
      'Shipping Country': { keyName: 'shippingCountry', type: 'string' },
      'Shipping Phone': { keyName: 'shippingPhone', type: 'string' },
      Notes: { keyName: 'notes', type: 'string' },
      'Note Attributes': { keyName: 'noteAttributes', type: 'string' },
      'Cancelled at': { keyName: 'cancelledAt', type: 'string' },
      'Payment Method': { keyName: 'paymentMethod', type: 'string' },
      'Payment Reference': { keyName: 'paymentReference', type: 'string' },
      'Refunded Amount': { keyName: 'refundedAmount', type: 'number' },
      Vendor: { keyName: 'vendor', type: 'string' },
      'Outstanding Balance': { keyName: 'outstanding', type: 'number' },
      Employee: { keyName: 'employee', type: 'string' },
      Location: { keyName: 'location', type: 'string' },
      'Device ID': { keyName: 'deviceId', type: 'string' },
      Id: { keyName: 'id', type: 'number' },
      Tags: { keyName: 'tags', type: 'string' },
      'Risk Level': { keyName: 'riskLevel', type: 'string' },
      Source: { keyName: 'source', type: 'string' },
      'Lineitem discount': { keyName: 'lineitemDiscount', type: 'number' },
      'Tax 1 Name': { keyName: 'tax1Name', type: 'string' },
      'Tax 1 Value': { keyName: 'tax1Value', type: 'string' },
      'Tax 2 Name': { keyName: 'tax2Name', type: 'string' },
      'Tax 2 Value': { keyName: 'tax2Value', type: 'string' },
      'Tax 3 Name': { keyName: 'tax3Name', type: 'string' },
      'Tax 3 Value': { keyName: 'tax3Value', type: 'string' },
      'Tax 4 Name': { keyName: 'tax4Name', type: 'string' },
      'Tax 4 Value': { keyName: 'tax4Value', type: 'string' },
      'Tax 5 Name': { keyName: 'tax5Name', type: 'string' },
      'Tax 5 Value': { keyName: 'tax5Value', type: 'string' },
      Phone: { keyName: 'phone', type: 'string' },
      'Receipt Number': { keyName: 'receiptNumber', type: 'string' },
      Duties: { keyName: 'duties', type: 'string' },
      'Billing Province Name': { keyName: 'billingProvinceName', type: 'string' },
      'Shipping Province Name': { keyName: 'shippingProvinceName', type: 'string' },
      'Payment ID': { keyName: 'paymentId', type: 'string' },
      'Payment Terms Name': { keyName: 'paymentTermsName', type: 'string' },
      'Next Payment Due At': { keyName: 'nextPaymentDueAt', type: 'string' },
      'Payment References': { keyName: 'paymentReferences', type: 'string' }
    }
  },
  shopee: {
    stringHeaderMapping: [
      'หมายเลขคำสั่งซื้อ',
      'สถานะการสั่งซื้อ',
      'สถานะการคืนเงินหรือคืนสินค้า',
      'ชื่อผู้ใช้ (ผู้ซื้อ)',
      'วันที่ทำการสั่งซื้อ',
      'เวลาการชำระสินค้า',
      'ช่องทางการชำระเงิน',
      'ช่องทางการชำระเงิน (รายละเอียด)',
      'แผนการผ่อนชำระ',
      'ค่าธรรมเนียม (%)',
      'ตัวเลือกการจัดส่ง',
      'วิธีการจัดส่ง',
      '*หมายเลขติดตามพัสดุ',
      'วันที่คาดว่าจะทำการจัดส่งสินค้า',
      'เวลาส่งสินค้า',
      'เลขอ้างอิง Parent SKU',
      'ชื่อสินค้า',
      'เลขอ้างอิง SKU (SKU Reference No.)',
      'ชื่อตัวเลือก',
      'ราคาตั้งต้น',
      'ราคาขาย',
      'จำนวน',
      'จำนวนที่ส่งคืน',
      'ราคาขายสุทธิ',
      'ส่วนลดจาก Shopee',
      'โค้ดส่วนลดชำระโดยผู้ขาย',
      'โค้ด Coins Cashback ชำระโดยผู้ขาย',
      'โค้ดส่วนลดชำระโดย Shopee (เช่น โค้ดจากโปรแกรม ร้านโค้ดคุ้ม, โค้ดส่วนลด Shopee, โค้ดส่วนลด Shopee Mall)',
      'โค้ดส่วนลด',
      'เข้าร่วมแคมเปญ bundle deal หรือไม่',
      'ส่วนลด bundle deal ชำระโดยผู้ขาย',
      'ส่วนลด bundle deal ชำระโดย Shopee',
      'ส่วนลดจากการใช้เหรียญ',
      'โปรโมชั่นช่องทางชำระเงินทั้งหมด',
      'ค่าคอมมิชชั่น',
      'Transaction Fee',
      'ราคาสินค้าที่ชำระโดยผู้ซื้อ (THB)',
      'ค่าจัดส่งที่ชำระโดยผู้ซื้อ',
      'ค่าจัดส่งที่ Shopee ออกให้โดยประมาณ',
      'ค่าจัดส่งสินค้าคืน',
      'ค่าบริการ',
      'จำนวนเงินทั้งหมด',
      'ค่าจัดส่งโดยประมาณ',
      'ชื่อผู้รับ',
      'หมายเลขโทรศัพท์',
      'หมายเหตุจากผู้ซื้อ',
      'ที่อยู่ในการจัดส่ง',
      'ประเทศ',
      'จังหวัด',
      'เขต/อำเภอ',
      'รหัสไปรษณีย์',
      'ประเภทคำสั่งซื้อ',
      'เวลาที่ทำการสั่งซื้อสำเร็จ',
      'บันทึก',
      'ผู้ซื้อร้องขอใบกำกับภาษี',
      'ประเภทใบกำกับภาษี',
      'ชื่อ',
      'ประเภทสาขา',
      'ชื่อสาขา',
      'รหัสประจำสาขา',
      'ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป',
      'รายละเอียดที่อยู่',
      'แขวง/ตำบล',
      'เขต/อำเภอ',
      'จังหวัด',
      'รหัสไปรษณีย์',
      'หมายเลขประจำตัวผู้เสียภาษี',
      'หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี',
      'อีเมลสำหรับรับใบกำกับภาษี',
      'Category',
      'SOR / Apas Number',
      'codesales',
      'ใบเสร็จ/ใบกำกับภาษี'
    ],
    objectColumnMapping: {
      A: 'orderId', //หมายเลขคำสั่งซื้อ
      B: 'orderStatus', //สถานะการสั่งซื้อ
      C: 'refundStatus', //สถานะการคืนเงินหรือคืนสินค้า
      D: 'buyerName', //ชื่อผู้ใช้ (ผู้ซื้อ)
      E: 'orderDate', //วันที่ทำการสั่งซื้อ
      F: 'paymentTime', //เวลาการชำระสินค้า
      G: 'paymentMethod', //ช่องทางการชำระเงิน
      H: 'paymentDetails', //ช่องทางการชำระเงิน (รายละเอียด)
      I: 'installmentPlan', //แผนการผ่อนชำระ
      J: 'transactionFeePercent', //ค่าธรรมเนียม (%)
      K: 'shippingOption', //ตัวเลือกการจัดส่ง
      L: 'shippingMethod', //วิธีการจัดส่ง
      M: 'trackingNumber', //*หมายเลขติดตามพัสดุ
      N: 'estimatedDeliveryDate', //วันที่คาดว่าจะทำการจัดส่งสินค้า
      O: 'deliveryTime', //เวลาส่งสินค้า
      P: 'parentSku', //เลขอ้างอิง Parent SKU
      Q: 'productName', // ชื่อสินค้า
      R: 'skuReferenceNo', //เลขอ้างอิง SKU (SKU Reference No.)
      S: 'optionName', //ชื่อตัวเลือก
      T: 'originalPrice', //ราคาตั้งต้น
      U: 'salePrice', //ราคาขาย
      V: 'quantity', //จำนวน
      W: 'returnedQuantity', //จำนวนที่ส่งคืน
      X: 'netSalePrice', //ราคาขายสุทธิ
      Y: 'shopeeDiscount', //ส่วนลดจาก shopee
      Z: 'sellerVoucher', //โค้ดส่วนลดชำระโดยผู้ขาย
      AA: 'coinsCashbackSeller', //โค้ด Coins Cashback ชำระโดยผู้ขาย
      AB: 'shopeeVoucher', //โค้ดส่วนลดชำระโดย Shopee (เช่น โค้ดจากโปรแกรม ร้านโค้ดคุ้ม, โค้ดส่วนลด Shopee, โค้ดส่วนลด Shopee Mall)
      AC: 'discountCode', //โค้ดส่วนลด
      AD: 'bundleDeal', //เข้าร่วมแคมเปญ bundle deal หรือไม่
      AE: 'bundleDiscountSeller', //ส่วนลด bundle deal ชำระโดยผู้ขาย
      AF: 'bundleDiscountShopee', //ส่วนลด bundle deal ชำระโดย Shopee
      AG: 'coinsUsed', //ส่วนลดจากการใช้เหรียญ
      AH: 'allPaymentPromotions', //โปรโมชั่นช่องทางชำระเงินทั้งหมด
      AI: 'commissionFee', //ค่าคอมมิชชั่น
      AJ: 'transactionFee', //ค่าบริการ
      AK: 'totalBuyerPaid', //ราคาสินค้าที่ชำระโดยผู้ซื้อ (THB)
      AL: 'shippingFeeBuyer', //ค่าจัดส่งที่ชำระโดยผู้ซื้อ
      AM: 'shippingFeeShopee', //ค่าจัดส่งที่ Shopee ออกให้โดยประมาณ
      AN: 'returnShippingFee', //ค่าจัดส่งสินค้าคืน
      AO: 'serviceFee', //ค่าบริการ
      AP: 'totalAmount', //จำนวนเงินทั้งหมด
      AQ: 'estimatedShippingFee', //ค่าจัดส่งโดยประมาณ
      AR: 'receiverName', //ชื่อผู้รับ
      AS: 'receiverPhone', //หมายเลขโทรศัพท์
      AT: 'buyerNote', //หมายเหตุจากผู้ซื้อ
      AU: 'shippingAddress', //ที่อยู่ในการจัดส่ง
      AV: 'shippingCountry', //ประเทศ
      AW: 'shippingProvince', //จังหวัด
      AX: 'shippingDistrict', //เขต/อำเภอ
      AY: 'shippingPostalCode', //รหัสไปรษณีย์
      AZ: 'orderType', //ประเภทคำสั่งซื้อ
      BA: 'orderSuccessTime', //เวลาที่ทำการสั่งซื้อสำเร็จ
      BB: 'orderNotes', //บันทึก
      BC: 'buyerInvoiceRequest', //ผู้ซื้อร้องขอใบกำกับภาษี
      BD: 'invoiceType', //ประเภทใบกำกับภาษี
      BE: 'invoiceName', //ชื่อ
      BF: 'invoiceBranchType', //ประเภทสาขา
      BG: 'invoiceBranchName', //ชื่อสาขา
      BH: 'invoiceBranchCode', //รหัสประจำสาขา
      BI: 'invoiceFullAddress', //ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป
      BJ: 'invoiceAddressDetails', //รายละเอียดที่อยู่
      BK: 'invoiceSubDistrict', //แขวง/ตำบล
      BL: 'invoiceDistrict', //เขต/อำเภอ
      BM: 'invoiceProvince', //จังหวัด
      BN: 'invoicePostalCode', //รหัสไปรษณีย์
      BO: 'taxpayerId', //หมายเลขประจำตัวผู้เสียภาษี
      BP: 'invoicePhoneNumber', //หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี
      BQ: 'invoiceEmail', //อีเมลสำหรับรับใบกำกับภาษี
      BR: 'category', //
      BS: 'SOR_ApasNumber', //SOR / Apas Number
      BT: 'codeSales', //codesales
      BU: 'invoiceReceipt' //ใบเสร็จ/ใบกำกับภาษี
    },
    stringColumnMapping: [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'AC',
      'AD',
      'AR',
      'AS',
      'AT',
      'AU',
      'AV',
      'AW',
      'AX',
      'AY',
      'AZ',
      'BA',
      'BB',
      'BC',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BK',
      'BL',
      'BM',
      'BN',
      'BO',
      'BP',
      'BQ',
      'BR',
      'BS',
      'BT',
      'BU'
    ],
    numberColumnMapping: ['T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'AA', 'AB', 'AE', 'AF', 'AG', 'AH', 'AI', 'AJ', 'AK', 'AL', 'AM', 'AN', 'AO', 'AP', 'AQ'],
    headerObjectMapping: {
      หมายเลขคำสั่งซื้อ: { keyName: 'orderId', type: 'string' },
      สถานะการสั่งซื้อ: { keyName: 'orderStatus', type: 'string' },
      สถานะการคืนเงินหรือคืนสินค้า: { keyName: 'refundStatus', type: 'string' },
      'ชื่อผู้ใช้ (ผู้ซื้อ)': { keyName: 'buyerName', type: 'string' },
      วันที่ทำการสั่งซื้อ: { keyName: 'orderDate', type: 'string' },
      เวลาการชำระสินค้า: { keyName: 'paymentTime', type: 'string' },
      ช่องทางการชำระเงิน: { keyName: 'paymentMethod', type: 'string' },
      'ช่องทางการชำระเงิน (รายละเอียด)': { keyName: 'paymentDetails', type: 'string' },
      แผนการผ่อนชำระ: { keyName: 'installmentPlan', type: 'string' },
      'ค่าธรรมเนียม (%)': { keyName: 'transactionFeePercent', type: 'string' },
      ตัวเลือกการจัดส่ง: { keyName: 'shippingOption', type: 'string' },
      วิธีการจัดส่ง: { keyName: 'shippingMethod', type: 'string' },
      '*หมายเลขติดตามพัสดุ': { keyName: 'trackingNumber', type: 'string' },
      วันที่คาดว่าจะทำการจัดส่งสินค้า: { keyName: 'estimatedDeliveryDate', type: 'string' },
      เวลาส่งสินค้า: { keyName: 'deliveryTime', type: 'string' },
      'เลขอ้างอิง Parent SKU': { keyName: 'parentSku', type: 'string' },
      ชื่อสินค้า: { keyName: 'productName', type: 'string' },
      'เลขอ้างอิง SKU (SKU Reference No.)': { keyName: 'skuReferenceNo', type: 'string' },
      ชื่อตัวเลือก: { keyName: 'optionName', type: 'string' },
      ราคาตั้งต้น: { keyName: 'originalPrice', type: 'number' },
      ราคาขาย: { keyName: 'salePrice', type: 'number' },
      จำนวน: { keyName: 'quantity', type: 'number' },
      จำนวนที่ส่งคืน: { keyName: 'returnedQuantity', type: 'number' },
      ราคาขายสุทธิ: { keyName: 'netSalePrice', type: 'number' },
      'ส่วนลดจาก Shopee': { keyName: 'shopeeDiscount', type: 'number' },
      โค้ดส่วนลดชำระโดยผู้ขาย: { keyName: 'sellerVoucher', type: 'number' },
      'โค้ด Coins Cashback ชำระโดยผู้ขาย': { keyName: 'coinsCashbackSeller', type: 'number' },
      'โค้ดส่วนลดชำระโดย Shopee (เช่น โค้ดจากโปรแกรม ร้านโค้ดคุ้ม}, โค้ดส่วนลด Shopee}, โค้ดส่วนลด S           Shopee Mall)': { keyName: 'shopeeVoucher', type: 'number' },
      โค้ดส่วนลด: { keyName: 'discountCode', type: 'string' },
      'เข้าร่วมแคมเปญ bundle deal หรือไม่': { keyName: 'bundleDeal', type: 'string' },
      'ส่วนลด bundle deal ชำระโดยผู้ขาย': { keyName: 'bundleDiscountSeller', type: 'number' },
      'ส่วนลด bundle deal ชำระโดย Shopee': { keyName: 'bundleDiscountShopee', type: 'number' },
      ส่วนลดจากการใช้เหรียญ: { keyName: 'coinsUsed', type: 'number' },
      โปรโมชั่นช่องทางชำระเงินทั้งหมด: { keyName: 'allPaymentPromotions', type: 'number' },
      ส่วนลดเครื่องเก่าแลกใหม่: { keyName: 'commissionFee', type: 'number' },
      โบนัสส่วนลดเครื่องเก่าแลกใหม่: { keyName: 'transactionFee', type: 'number' },
      ค่าคอมมิชชั่น: { keyName: 'commissionFee', type: 'number' },
      'Transaction Fee': { keyName: 'transactionFee', type: 'number' },
      'ราคาสินค้าที่ชำระโดยผู้ซื้อ (THB)': { keyName: 'totalBuyerPaid', type: 'number' },
      ค่าจัดส่งที่ชำระโดยผู้ซื้อ: { keyName: 'shippingFeeBuyer', type: 'number' },
      'ค่าจัดส่งที่ Shopee ออกให้โดยประมาณ': { keyName: 'shippingFeeShopee', type: 'number' },
      ค่าจัดส่งสินค้าคืน: { keyName: 'returnShippingFee', type: 'number' },
      ค่าบริการ: { keyName: 'serviceFee', type: 'number' },
      จำนวนเงินทั้งหมด: { keyName: 'totalAmount', type: 'number' },
      ค่าจัดส่งโดยประมาณ: { keyName: 'estimatedShippingFee', type: 'number' },
      โบนัสส่วนลดเครื่องเก่าแลกใหม่จากผู้ขาย: { keyName: 'bonusDiscountTradeIn', type: 'number' },
      ชื่อผู้รับ: { keyName: 'receiverName', type: 'string' },
      หมายเลขโทรศัพท์: { keyName: 'receiverPhone', type: 'string' },
      หมายเหตุจากผู้ซื้อ: { keyName: 'buyerNote', type: 'string' },
      ที่อยู่ในการจัดส่ง: { keyName: 'shippingAddress', type: 'string' },
      ประเทศ: { keyName: 'shippingCountry', type: 'string' },
      จังหวัด: { keyName: 'shippingProvince', type: 'string' },
      'เขต/อำเภอ': { keyName: 'shippingDistrict', type: 'string' },
      รหัสไปรษณีย์: { keyName: 'shippingPostalCode', type: 'string' },
      ประเภทคำสั่งซื้อ: { keyName: 'orderType', type: 'string' },
      เวลาที่ทำการสั่งซื้อสำเร็จ: { keyName: 'orderSuccessTime', type: 'string' },
      บันทึก: { keyName: 'orderNotes', type: 'string' },
      ผู้ซื้อร้องขอใบกำกับภาษี: { keyName: 'buyerInvoiceRequest', type: 'string' },
      ประเภทใบกำกับภาษี: { keyName: 'invoiceType', type: 'string' },
      ชื่อ: { keyName: 'invoiceName', type: 'string' },
      ประเภทสาขา: { keyName: 'invoiceBranchType', type: 'string' },
      ชื่อสาขา: { keyName: 'invoiceBranchName', type: 'string' },
      รหัสประจำสาขา: { keyName: 'invoiceBranchCode', type: 'string' },
      ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป: { keyName: 'invoiceFullAddress', type: 'string' },
      รายละเอียดที่อยู่: { keyName: 'invoiceAddressDetails', type: 'string' },
      'แขวง/ตำบล': { keyName: 'invoiceSubDistrict', type: 'string' },
      'เขต/อำเภอ_1': { keyName: 'invoiceDistrict', type: 'string' },
      จังหวัด_1: { keyName: 'invoiceProvince', type: 'string' },
      รหัสไปรษณีย์_1: { keyName: 'invoicePostalCode', type: 'string' },
      หมายเลขประจำตัวผู้เสียภาษี: { keyName: 'taxpayerId', type: 'string' },
      หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี: { keyName: 'invoicePhoneNumber', type: 'string' },
      อีเมลสำหรับรับใบกำกับภาษี: { keyName: 'invoiceEmail', type: 'string' }
    }
  },
  lazada: {
    stringHeaderMapping: [],
    objectColumnMapping: {},
    stringColumnMapping: [],
    numberColumnMapping: [],
    headerObjectMapping: {}
  },
  productMaster: {
    stringHeaderMapping: ['Plnt', 'Material', 'Material Number', 'MG 1', 'MG 2', 'Profit Ctr', 'BUn', 'MTyp', 'Profl.'],
    objectColumnMapping: {
      A: 'plant',
      B: 'material',
      C: 'materialNumber',
      D: 'mg1',
      E: 'mg2',
      F: 'profitCenter',
      G: 'baseUnit',
      H: 'materialType',
      I: 'profile'
    },
    stringColumnMapping: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    numberColumnMapping: []
  },
  tiktok: {
    stringHeaderMapping: [
      'Order ID',
      'Order Status',
      'Order Substatus',
      'Cancelation/Return Type',
      'Normal or Pre-order',
      'SKU ID',
      'Seller SKU',
      'Product Name',
      'Variation',
      'Quantity',
      'Sku Quantity of return',
      'SKU Unit Original Price',
      'SKU Subtotal Before Discount',
      'SKU Platform Discount',
      'SKU Seller Discount',
      'SKU Subtotal After Discount',
      'Shipping Fee After Discount',
      'Original Shipping Fee',
      'Shipping Fee Seller Discount',
      'Shipping Fee Platform Discount',
      'Taxes',
      'Small Order Fee',
      'Order Amount',
      'Order Refund Amount',
      'Created Time',
      'Paid Time',
      'RTS Time',
      'Shipped Time',
      'Delivered Time',
      'Cancelled Time',
      'Cancel By',
      'Cancel Reason',
      'Fulfillment Type',
      'Warehouse Name',
      'Tracking ID',
      'Delivery Option',
      'Shipping Provider Name',
      'Buyer Message',
      'Buyer Username',
      'Recipient',
      'Phone #',
      'Zipcode',
      'Country',
      'Province',
      'District',
      'Detail Address',
      'Additional Address Information',
      'Payment Method',
      'Weight(kg)',
      'Product Category',
      'Package ID',
      'Seller Note',
      'Checked Status',
      'Checked Marked By'
    ],
    objectColumnMapping: {
      A: 'orderId',
      B: 'orderStatus',
      C: 'orderSubstatus',
      D: 'cancelationReturnType',
      E: 'normalOrPreOrder',
      F: 'skuId',
      G: 'sellerSku',
      H: 'productName',
      I: 'variation',
      J: 'quantity',
      K: 'skuQuantityOfReturn',
      L: 'skuUnitOriginalPrice',
      M: 'skuSubtotalBeforeDiscount',
      N: 'skuPlatformDiscount',
      O: 'skuSellerDiscount',
      P: 'skuSubtotalAfterDiscount',
      Q: 'shippingFeeAfterDiscount',
      R: 'originalShippingFee',
      S: 'shippingFeeSellerDiscount',
      T: 'shippingFeePlatformDiscount',
      U: 'taxes',
      V: 'smallOrderFee',
      W: 'orderAmount',
      X: 'orderRefundAmount',
      Y: 'createdTime',
      Z: 'paidTime',
      AA: 'rtsTime',
      AB: 'shippedTime',
      AC: 'deliveredTime',
      AD: 'cancelledTime',
      AE: 'cancelBy',
      AF: 'cancelReason',
      AG: 'fulfillmentType',
      AH: 'warehouseName',
      AI: 'trackingId',
      AJ: 'deliveryOption',
      AK: 'shippingProviderName',
      AL: 'buyerMessage',
      AM: 'buyerUsername',
      AN: 'recipient',
      AO: 'phone',
      AP: 'zipcode',
      AQ: 'country',
      AR: 'province',
      AS: 'district',
      AT: 'detailAddress',
      AU: 'additionalAddressInformation',
      AV: 'paymentMethod',
      AW: 'weight',
      AX: 'productCategory',
      AY: 'packageId',
      AZ: 'sellerNote',
      BA: 'checkedStatus',
      BB: 'checkedMarkedBy'
    },
    stringColumnMapping: [],
    numberColumnMapping: [],
    headerObjectMapping: {
      'Order ID': { keyName: 'orderId', type: 'string' },
      'Order Status': { keyName: 'orderStatus', type: 'string' },
      'Order Substatus': { keyName: 'orderSubstatus', type: 'string' },
      'Cancelation/Return Type': { keyName: 'cancelationReturnType', type: 'string' },
      'Normal or Pre-order': { keyName: 'normalOrPreOrder', type: 'string' },
      'SKU ID': { keyName: 'skuId', type: 'string' },
      'Seller SKU': { keyName: 'sellerSku', type: 'number' },
      'Product Name': { keyName: 'productName', type: 'string' },
      Variation: { keyName: 'variation', type: 'string' },
      Quantity: { keyName: 'quantity', type: 'number' },
      'Sku Quantity of return': { keyName: 'skuQuantityOfReturn', type: 'number' },
      'SKU Unit Original Price': { keyName: 'skuUnitOriginalPrice', type: 'number' },
      'SKU Subtotal Before Discount': { keyName: 'skuSubtotalBeforeDiscount', type: 'number' },
      'SKU Platform Discount': { keyName: 'skuPlatformDiscount', type: 'number' },
      'SKU Seller Discount': { keyName: 'skuSellerDiscount', type: 'number' },
      'SKU Subtotal After Discount': { keyName: 'skuSubtotalAfterDiscount', type: 'number' },
      'Shipping Fee After Discount': { keyName: 'shippingFeeAfterDiscount', type: 'number' },
      'Original Shipping Fee': { keyName: 'originalShippingFee', type: 'number' },
      'Shipping Fee Seller Discount': { keyName: 'shippingFeeSellerDiscount', type: 'number' },
      'Shipping Fee Platform Discount': { keyName: 'shippingFeePlatformDiscount', type: 'number' },
      Taxes: { keyName: 'taxes', type: 'number' },
      'Small Order Fee': { keyName: 'smallOrderFee', type: 'number' },
      'Order Amount': { keyName: 'orderAmount', type: 'number' },
      'Order Refund Amount': { keyName: 'orderRefundAmount', type: 'number' },
      'Created Time': { keyName: 'createdTime', type: 'string' },
      'Paid Time': { keyName: 'paidTime', type: 'string' },
      'RTS Time': { keyName: 'rtsTime', type: 'string' },
      'Shipped Time': { keyName: 'shippedTime', type: 'string' },
      'Delivered Time': { keyName: 'deliveredTime', type: 'string' },
      'Cancelled Time': { keyName: 'cancelledTime', type: 'string' },
      'Cancel By': { keyName: 'cancelBy', type: 'string' },
      'Cancel Reason': { keyName: 'cancelReason', type: 'string' },
      'Fulfillment Type': { keyName: 'fulfillmentType', type: 'string' },
      'Warehouse Name': { keyName: 'warehouseName', type: 'string' },
      'Tracking ID': { keyName: 'trackingId', type: 'string' },
      'Delivery Option': { keyName: 'deliveryOption', type: 'string' },
      'Shipping Provider Name': { keyName: 'shippingProviderName', type: 'string' },
      'Buyer Message': { keyName: 'buyerMessage', type: 'string' },
      'Buyer Username': { keyName: 'buyerUsername', type: 'string' },
      Recipient: { keyName: 'recipient', type: 'string' },
      'Phone #': { keyName: 'phone', type: 'string' },
      Zipcode: { keyName: 'zipcode', type: 'string' },
      Country: { keyName: 'country', type: 'string' },
      Province: { keyName: 'province', type: 'string' },
      District: { keyName: 'district', type: 'string' },
      'Detail Address': { keyName: 'detailAddress', type: 'string' },
      'Additional address information': { keyName: 'additionalAddressInformation', type: 'string' },
      'Payment Method': { keyName: 'paymentMethod', type: 'string' },
      'Weight(kg)': { keyName: 'weight', type: 'number' },
      'Product Category': { keyName: 'productCategory', type: 'string' },
      'Package ID': { keyName: 'packageId', type: 'string' },
      'Seller Note': { keyName: 'sellerNote', type: 'string' },
      'Checked Status': { keyName: 'checkedStatus', type: 'string' },
      'Checked Marked by': { keyName: 'checkedMarkedBy', type: 'string' }
    }
  }
}
