import { StringifyOptions } from 'node:querystring'

export interface iQueryOrderTransaction {
  searchStart: string
  searchEnd: string
  typePlatform: string
  invoiceNumber: string
  userId?: number
  username?: string
  purchaseOrder?: string
  name?: string
  name2?: string
  firstname?: string
  lastname?: string
  profitCenter?: string
  materialProductCode?: string
  accountCode?: number
  salesmanCode?: number
  invoiceDate?: string
  address?: string
  address2?: string
  address3?: string
  postCode?: string
  city?: string
  tel?: string
  requireTaxInvoice?: boolean
  taxId?: string
  itemCat?: string
  quantity?: number
  mg4?: string
  UOM?: string
  storageLocation?: string
  SORPrice?: number
  search?: string
}

export interface iShopeeBody {
  accountCode: number
  salesmanCode: Number
  purchaseOrder: string
  invoiceDate: string //'DATE'
  name: string
  address: string
  postCode: string
  city: string
  tel: string
  taxId: number
  materialProductCode: StringifyOptions
  itemCat: string
  quantity: 0
  mg4: string
  profitCenter: string
  UOM: string
  plant: string
  storageLocation: string
  SORPrice: number
  invoiceEmail: string
  orderStatus: string
  refundStatus: string
  buyerName: string
  orderDate: string //'DATE'
  paymentMethod: string
  paymentDetails: string
  installmentPlan: string
  transactionFeePercent: string
  shippingOption: string
  shippingMethod: string
  trackingNumber: string
  estimatedDeliveryDate: string // 'DATE'
  deliveryTime: string
  parentSku: string
  productName: string
  optionName: string
  originalPrice: number
  salePrice: number
  returnedQuantity: number
  netSalePrice: number
  shopeeDiscount: number
  sellerVoucher: number
  coinsCashbackSeller: number
  shopeeVoucher: number
  discountCode: string
  bundleDeal: string
  bundleDiscountSeller: number
  bundleDiscountShopee: number
  coinsUsed: number
  allPaymentPromotions: number
  commissionFee: number
  transactionFee: number
  totalBuyerPaid: number
  shippingFeeBuyer: number
  shippingFeeShopee: number
  returnShippingFee: number
  serviceFee: number
  estimatedShippingFee: number
  receiverName: string
  buyerNote: string
  shippingCountry: string
  shippingDistrict: string
  orderType: string
  orderSuccessTime: string
  orderNotes: string
  buyerInvoiceRequest: string
  invoiceType: string
  invoiceName: string
  invoiceBranchType: string
  invoiceBranchName: string
  invoiceBranchCode: string
  invoiceFullAddress: string
  invoiceAddressDetails: string
  invoiceSubDistrict: string
  invoiceDistrict: string
  invoiceProvince: string
  invoicePostalCode: string
  taxpayerId: string
  invoicePhoneNumber: string
  category: string
  SOR_ApasNumber: string
  codeSales: string
  invoiceReceipt: string
}

export interface iPlatform {
  shopify: {
    allowedFields: string[]
  }
  shopee: {
    allowedFields: string[]
  }
  lazada: {
    allowedFields: string[]
  }
}

export interface iBodyOrderTransactionCreate {
  accountCode: number
  salesmanCode: number
  plant: string
  storageLocation: string
  country: string
}

export interface iResultShopifyItem {
  id: number
  name: string
  lineitemName: string
  lineitemQuantity: number
  lineitemPrice: number
  lineitemSubtotal?: number
  subtotal: number
  calDiscountAmount?: number
  calDiscountPerItem?: number
  calDiscountAmountPerItem?: number
  calNetPrice?: number
  financialStatus?: string
  fulfillmentStatus?: string
  paidAt?: number
  fulfilledAt?: string
  acceptsMarketing?: string
  currency?: string
  shipping?: number
  taxes?: number
  total: number
  discountCode?: string
  discountAmount?: number
  billingName?: string
  billingStreet?: string
  billingAddress1?: string
  billingCity?: string
  billingZip?: string
  billingProvince?: string
  billingCountry?: string
  billingPhone?: string
  shippingName?: string
  shippingStreet?: string
  shippingAddress1?: string
  shippingCity?: string
  shippingZip?: string
  shippingProvince?: string
  shippingCountry?: string
  shippingPhone?: string
  paymentMethod?: string
  paymentReference?: string
  refundedAmount?: number
  outstanding?: number
  employee?: string
  riskLevel?: string
  source?: string
  billingProvinceName?: string
  shippingProvinceName?: string
  paymentId?: string
  paymentReferences?: string
  vendor: string
  lineitemDiscount: number
  createdAt: number
  lineitemSku: string
  lineitemRequiresShipping?: boolean
  lineitemTaxable?: boolean
  lineitemFulfillmentStatus?: string
  noteAttributes?: string
  subtotalErrorCase?: boolean
  profitCenter?: string
}

export interface iResultTiktokItem {
  orderId?: string
  orderStatus?: string
  orderSubstatus?: string
  cancelationReturnType?: string
  normalOrPreOrder?: string
  skuId?: string
  sellerSku?: number
  productName?: string
  variation?: string
  quantity?: number
  skuQuantityOfReturn?: number
  skuUnitOriginalPrice?: number
  skuSubtotalBeforeDiscount?: number
  skuPlatformDiscount?: number
  skuSellerDiscount?: number
  skuSubtotalAfterDiscount?: number
  shippingFeeAfterDiscount?: number
  originalShippingFee?: number
  shippingFeeSellerDiscount?: number
  shippingFeePlatformDiscount?: number
  taxes?: number
  smallOrderFee?: number
  orderAmount?: number
  orderRefundAmount?: number
  createdTime?: string
  paidTime?: string
  rtsTime?: string
  shippedTime?: string
  deliveredTime?: string
  cancelledTime?: StringifyOptions
  cancelBy?: string
  cancelReason?: string
  fulfillmentType?: string
  warehouseName?: string
  trackingId?: string
  deliveryOption?: string
  shippingProviderName?: string
  buyerMessage?: string
  buyerUsername?: string
  recipient?: string
  phone?: string
  zipcode?: string
  country?: string
  province?: string
  district?: string
  detailAddress?: string
  additionalAddressInformation?: string
  paymentMethod?: string
  weight?: number
  productCategory?: string
  packageId?: string
  sellerNote?: string
  checkedStatus?: string
  checkedMarkedBy?: string
  profitCenter?: string
}

export interface iResultShopeeItem {
  orderId: string
  paymentTime: string
  buyerName: string
  shippingAddress: string
  shippingPostalCode: string
  shippingProvince: string
  receiverPhone: string
  skuReferenceNo: string
  quantity: number
  invoiceEmail: string
  orderStatus: string
  refundStatus: string
  orderDate: string
  paymentMethod: string
  paymentDetails: string
  installmentPlan: string
  transactionFeePercent: number
  shippingOption: string
  shippingMethod: string
  trackingNumber: string
  estimatedDeliveryDate: string
  deliveryTime: string
  parentSku: string
  productName: string
  optionName: string
  originalPrice: number
  salePrice: number
  returnedQuantity: number
  netSalePrice: number
  shopeeDiscount: number
  sellerVoucher: number
  coinsCashbackSeller: number
  shopeeVoucher: number
  discountCode: number
  bundleDeal: string
  bundleDiscountSeller: number
  bundleDiscountShopee: number
  coinsUsed: number
  allPaymentPromotions: number
  commissionFee: number
  transactionFee: number
  totalBuyerPaid: number
  shippingFeeBuyer: number
  shippingFeeShopee: number
  returnShippingFee: number
  serviceFee: number
  totalAmount: number
  estimatedShippingFee: number
  receiverName: string
  buyerNote: string
  shippingCountry: string
  shippingDistrict: string
  orderType: string
  orderSuccessTime: string
  orderNotes: string
  buyerInvoiceRequest: string
  invoiceType: string
  invoiceName: string
  invoiceBranchType: string
  invoiceBranchName: string
  invoiceBranchCode: string
  invoiceFullAddress: string
  invoiceAddressDetails: string
  invoiceSubDistrict: string
  invoiceDistrict: string
  invoiceProvince: string
  invoicePostalCode: string
  taxpayerId: string
  invoicePhoneNumber: string
  category: string
  SOR_ApasNumber: string
  codeSales: string
  invoiceReceipt: string
  profitCenter?: string
}
